### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by TwanoO67** [fbedussi/reveal-js-editor#26]
Hello @fbedussi 

I'm trying to launch the project, after having `npm install; npm start`
I'm having an electron app beeing launch, but it's all white.

What is the next step ? Am I missing something ?

**Comment by fbedussi** [comment]
Hi @TwanoO67, you are right the bundled js was missing, I've just pushed it, so either pull the project or just run ````npm run dev```` to build js on your machine. 

Thanks

P.S. Wich SO are you running? I've not optimized for OSX yet.

**Comment by TwanoO67** [comment]
I'm in fact running Osx yes ^^

Is it a way to run this on mac, even in a non optimised way ?
