### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by TwanoO67** [fbedussi/reveal-js-editor#28]
I'm testing on macOs (so it's maybe related)

Those buttons are working fine:
- Open markdown file
- Save presentation

But those are not working:
- Insert slide
- Insert image
- Open preview window

the same functionnalities are working well when called from the menubar 
( Insert/Slides , Insert/Image, Preview / Show preview in this window)

**Comment by fbedussi** [comment]
Thanks for the feedback. If you pull the latest version it should be fixed. It was not OSX related, I just forgot to handle the click on those buttons!
